name: Android CI

on: pull_request

jobs:
  check:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup jdk
        uses: actions/setup-java@v2
        with:
          java-version: 11
      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3
          bundler-cache: true
      - name: run lint
        run: ./gradlew lint
      - name: run detekt
        run: ./gradlew detekt
      - name: run unit test
        run: ./gradlew testDebugUnitTest
      - name: run connected test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          script: ./gradlew connectedDebugAndroidTest
      - name: Jacoco
        run: ./gradlew jacocoMergedReport
      - name: Danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gem install bundler
          bundle update
          bundle install
          bundle exec danger
#      - name: Upload Coverage
#        uses: codecov/codecov-action@v1
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          files: ./build/reports/jacoco/jacocoMergedReport/jacocoMergedReport.xml
