name: Android CI

on: pull_request

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Gradle Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/**
            ~/**/build/**
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts*') }}
      - name: Build with Gradle
        run: ./gradlew assembleDebug --stacktrace

  test:
    needs: setup
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Unit Test
        run: ./gradlew testDebug --stacktrace
      - name: Instrumented Unit Test
        uses: reactivecircus/android-emulator-runner@v2.14.3
        with:
          api-level: 29
          arch: x86_64
          script: ./gradlew connectedCheck --stacktrace --continue
      - name: Jacoco
        run: ./gradlew jacocoTestReport
      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Gradle Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/**
            ~/**/build/**
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts*') }}
      - name: run lint
        run: ./gradlew lint
      - name: run ktlint
        run: ./gradlew ktlintCheck
      - name: Cache Gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-danger-${{ env.cache-name }}-gems-${{ hashFiles('**/Gemfile') }}
      - name: run danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gem install bundler:1.17.2
          bundle update
          bundle install
          bundle exec danger
