name: Android CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup jdk
        uses: actions/setup-java@v2
        with:
          distribution: 'liberica'
          java-version: 11
      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3
          bundler-cache: true
      - name: setup gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
            ~/.android/cache
          key: ${{ runner.os }}-v1-gradle-${{ hashFiles('**/gradle-wrapper.properties', '**/*.toml') }}
      - name: run lint
        run: ./gradlew lintDebug
      - name: run detekt
        run: ./gradlew detekt
      - name: run unit test
        run: ./gradlew testDebugUnitTest --continue
      - name: run connected test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedDebugAndroidTest --continue
      - name: create jacoco report
        run: ./gradlew jacocoMergedReport
      - name: run danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bundle exec danger
      - name: upload coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/reports/jacoco/jacocoMergedReport/jacocoMergedReport.xml

  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run qodana
        uses: JetBrains/qodana-action@v4.2.5
        with:
          linter: jetbrains/qodana-jvm-android:latest
