name: Android CI

on: pull_request

jobs:
  setup:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Gradle Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/**
            ~/**/build/**
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts*') }}
      - name: Build with Gradle
        run: ./gradlew assembleDebug --stacktrace

  check:
    needs: setup
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Gradle Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/**
            ~/**/build/**
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts*') }}
      - name: run lint
        run: ./gradlew lint --stacktrace
      - name: run ktlint
        run: ./gradlew ktlintCheck --stacktrace
      - name: Unit Test
        run: ./gradlew test --stacktrace
      - name: Instrumented Test
        uses: reactivecircus/android-emulator-runner@v2.14.3
        with:
          api-level: 30
          arch: x86_64
          script: ./gradlew connectedCheck --stacktrace --continue
      - name: Jacoco
        run: ./gradlew jacocoMergedReport
      - name: Danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gem install bundler
          bundle update
          bundle install
          bundle exec danger
      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/reports/jacoco/jacocoMergedReport/jacocoMergedReport.xml
