name: Android CI Master

on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Gradle Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/**
            ~/**/build/**
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts*') }}
      - name: Build with Gradle
        run: ./gradlew assembleDebug --stacktrace

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Gradle Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/**
            ~/**/build/**
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts*') }}
      - name: Unit Test
        run: ./gradlew testDebug --stacktrace
      - name: Instrumented Unit Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck --stacktrace
      - name: Jacoco
        run: ./gradlew jacocoTestReport
      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
