name: Run auto update
on:
  repository_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  update_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: run auto update
        run: ./gradlew clean upgradeDependencies
        env:
          gitHubWriteToken: ${{ secrets.GITHUB_TOKEN }}
