name: Run auto update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  update_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup jdk
        uses: actions/setup-java@v2
        with:
          distribution: 'liberica'
          java-version: 11
      - name: setup gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
            ~/.android/cache
          key: ${{ runner.os }}-v1-gradle-${{ hashFiles('**/gradle-wrapper.properties', '**/*.toml') }}
      - name: run auto update
        run: ./gradlew upgradeDependencies
        env:
          gitHubWriteToken: ${{ secrets.GITHUB_TOKEN }}
          gitUserEmail: ${{ secrets.ACTIONS_USER_EMAIL }}
          gitUserName: ${{ secrets.ACTIONS_USER_NAME }}
          gitHubRepository: ${{ github.repository }}
